# flake8: noqa E501

MEAL_VOUCHER_CATEGORIES = [
    18,  # FRAIS,
    99,  # BOISSONS BASE DE CEREALES
    100,  # EAU
    101,  # JUS ET NECTARS
    102,  # SIROPS
    103,  # SODAS, LIMONADES, EAUX GAZEUSES
    106,  # ALIMENTS POUR ANIMAUX
    107,  # ALIMENTS POUR BEBES
    109,  # BISCUITERIE, VIENNOISERIE, PATISSERIE
    110,  # CAFE, CHICOREE EN PAQUET
    111,  # CHAMPIGNONS SECHES PRE-EMBALLES
    112,  # CHOCOLAT
    113,  # CONFISERIE
    114,  # CONFITURES ET PATES A TARTINER
    115,  # CONSERVES DE LEGUMES
    116,  # CONSERVES DE POISSONS ET D'ALGUES
    117,  # CONSERVES DE TOMATE
    118,  # CONSERVES DE VIANDES
    119,  # CROUTONS ET PANURES
    120,  # DESSERTS AMBIANTS
    121,  # FARINE, FECULE, SEMOULE, TAPIOCA, PUREE DE POMMES DE TERRE
    122,  # FRUITS SECS EN PAQUET
    123,  # HUILES ET VINAIGRES
    124,  # LAIT EN POUDRE, CONCENTRE, UHT
    125,  # LEGUMES SECS, RIZ, GRAINES, ETC EN PAQUET
    126,  # OLIVES CONDITIONNES
    127,  # PAIN DE LONGUE CONSERVATION
    128,  # PATES ALIMENTAIRES
    129,  # PATES ALIMENTAIRES ASIATIQUES
    130,  # PATES ALIMENTAIRES SANS GLUTEN
    131,  # PETITS DEJEUNERS
    132,  # PLATS CUISINES EN CONSERVE
    133,  # PRODUITS POUR PATISSERIE
    134,  # RIZ, CEREALES GROS CONDITIONNEMENTS
    135,  # CONDIMENTS ET SAUCES
    136,  # SOUPES ET POTAGES
    137,  # SUCRES ET EDULCORANTS
    138,  # THES, INFUSIONS EN SACHET
    139,  # VRAC
    140,  # BOISSONS LACTEES ET VEGETALES
    141,  # COMPLEMENTS ALIMENTAIRES FRAIS
    142,  # CREMERIE
    143,  # DESSERTS ET ENTREMETS FRAIS
    144,  # FRUITS ET LEGUMES
    145,  # JUS DE FRUIT FRAIS, AUTRES BOISSONS REFRIGERES
    146,  # OEUFS
    147,  # OLIVES EN VRAC
    148,  # PAINS ET PATISSERIE FRAICHE EN VRAC
    149,  # PAINS ET PATISSERIE FRAICHE PRE-EMBALLES
    150,  # PATES BRISES, CREPES ETC REFRIGERES
    151,  # PATES FRAICHES
    152,  # POISSONNERIE
    153,  # SOUPES ET POTAGES FRAIS
    154,  # SURGELE
    155,  # TOFU, TEMPEH, MISO
    156,  # TRAITEUR
    157,  # VIANDE
    277,  # ANTIPASTI ET TAPENADES
    278,  # BISCUITS APERITIFS
    279,  # CHIPS
    280,  # FRUITS A COQUE ET GRAINES EN PAQUET
    281,  # BISCUITS SUCRES
    282,  # GATEAUX
    283,  # CHOCOLAT AU LAIT TABLETTE
    284,  # CHOCOLAT DESSERT
    285,  # CHOCOLAT NOIR TABLETTE
    286,  # CHOCOLATS SPECIAUX
    287,  # BONBONS CARAMELS
    288,  # CHEWING-GUM ET PASTILLES
    289,  # COMPOTES
    290,  # CONFITURES FRUIT
    291,  # MIEL
    292,  # PATES A TARTINER
    293,  # HUILES
    294,  # HUILES AROMATISEES
    295,  # VINAIGRES
    296,  # BARRES CEREALES ET BISCUITS
    297,  # BISCOTTES
    298,  # BOISSONS INSTANT. PT. DEJEUNERS
    299,  # CEREALES EN PAQUET
    300,  # GALETTES SOUFFLEES
    301,  # CHOCOLAT ET CACAO CUISINE
    302,  # EPAISSISSANTS
    303,  # EXTRAITS ET AROMES
    304,  # FRUITS CONFITS ET POUDRES
    305,  # LEVAIN, LEVURE, FERMENTS
    306,  # PREPARATIONS PATISSERIE
    307,  # SUCRE VANILLE
    309,  # BOUILLONS
    310,  # CHUTNEYS
    312,  # EPICES CONDITIONNES
    313,  # LAIT DE COCO
    314,  # MAYONNAISE
    315,  # MOUTARDES
    316,  # PESTO
    317,  # PUREES D'OLEAGINEAUX
    318,  # SAUCES ET CREMES
    319,  # SAUCES ET PATES PIMENTEES
    320,  # SAUCES SOJA ET ASIATIQUES
    321,  # SAUCES TOMATES PREPAREES
    322,  # SELS
    323,  # BISCUITS
    324,  # CAFE
    325,  # CHOCOLAT, BONBONS RECONDITIONNES
    326,  # EPICES, HERBES, CHAMPIGNONS RECONDITIONNES
    327,  # FARINE, CEREALES, LEGUMINEUSES, FRUITS A COCQUES, ETC EN VRAC
    328,  # FRUITS SECS, GRAINES ETC RECONDITIONNES
    329,  # THE ET INFUSIONS RECONDITIONNES
    330,  # BEURRE
    331,  # CREME
    332,  # FROMAGE
    333,  # GRAISSES VEGETALES ET MARGARINES
    334,  # LAIT
    335,  # SUISSE ET FROMAGE FRAIS
    336,  # YAOURT
    337,  # FRUITS
    338,  # GRAINES GERMEES
    339,  # LEGUMES
    340,  # FRUITS SURGELES
    341,  # GLACE ET DESSERTS SURGELES
    342,  # LEGUMES SURGELES
    343,  # PIZZA, QUICHE, PLATS PREPARES SURGELES
    344,  # POISSON SURGELE
    345,  # VIANDE SURGELEE
    346,  # TRAITEUR, SALADES, PLATS PREPARES A BASE DE CEREALES, LEGUMES
    347,  # CHARCUTERIE ET SALAISONS
    348,  # PLATS PREPARES FRAIS A BASE DE VIANDE
    349,  # VIANDE D'AGNEAU ET DE MOUTON
    350,  # VIANDE DE BOEUF
    351,  # VIANDE DE PORC
    352,  # VIANDE DE VEAU
    353,  # VOLAILLE ET GIBIERS
    368,  # ACCESSOIRES DE MENAGE
    397,  # Conserves de fruits
    405,  # SUCRES ET EDULCORANTS
    418,  # LEGUMES
    427,  # Tous / En vente / ALIMENTAIRE / EPICERIE /EPICERIE / CAFE, CHICOREE ET MELANGES
    433,  #  En vente / ALIMENTAIRE / EPICERIE / CONDIMENTS ET SAUCES / CONDIMENTS
    443,  #  En vente / ALIMENTAIRE / EPICERIE / VRAC / THE ET INFUSIONS RECONDITIONNES
    444,  # chcolat
    445,  # plats
    448,  # ALIMENTAIRE / FRAIS / POISSONNERIE
    449,  # Tous / En vente / ALIMENTAIRE / EPICERIE / VRAC / BISCUITS SALES
    450,  # Tous / En vente / ALIMENTAIRE
]
