# flake8: noqa E501

MEAL_VOUCHER_CATEGORIES = [
    18,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS
    99,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / BOISSONS / BOISSONS BASE DE CEREALES
    101,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / BOISSONS / JUS ET NECTARS
    103,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / BOISSONS / SODAS, LIMONADES, EAUX GAZEUSES
    107,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / ALIMENTS POUR BEBES
    109,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / BISCUITERIE, VIENNOISERIE, PATISSERIE
    115,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / CONSERVES DE LEGUMES
    116,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / CONSERVES DE POISSONS ET D'ALGUES
    117,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / CONSERVES DE TOMATE
    118,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / CONSERVES DE VIANDES
    120,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / DESSERTS AMBIANTS
    124,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / LAIT EN POUDRE, CONCENTRE, UHT
    127,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / PAIN DE LONGUE CONSERVATION
    132,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / PLATS CUISINES EN CONSERVE
    136,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / SOUPES ET POTAGES
    140,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / BOISSONS LACTEES ET VEGETALES
    143,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / DESSERTS ET ENTREMETS FRAIS
    146,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / OEUFS
    148,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / PAINS ET PATISSERIE FRAICHE EN VRAC
    151,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / PATES FRAICHES
    152,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / POISSONNERIE
    281,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / BISCUITERIE, VIENNOISERIE, PATISSERIE / BISCUITS SUCRES
    282,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / BISCUITERIE, VIENNOISERIE, PATISSERIE / GATEAUX
    289,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / CONFITURES ET PATES A TARTINER / COMPOTES
    323,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / VRAC / BISCUITS
    332,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / CREMERIE / FROMAGE
    335,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / CREMERIE / SUISSE ET FROMAGE FRAIS
    336,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / CREMERIE / YAOURT
    337,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / FRUITS ET LEGUMES / FRUITS
    347,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / VIANDE / CHARCUTERIE ET SALAISONS
    351,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / VIANDE / VIANDE DE PORC
    353,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / VIANDE / VOLAILLE ET GIBIERS
    397,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / EPICERIE / Conserves de fruits
    418,  # ALIMENTAIRE / FRAIS/FROMAGE / ALIMENTAIRE / FRAIS / FRUITS ET LEGUMES / LEGUMES
    446,  # ALIMENTAIRE / FRAIS/FROMAGE
    447,  # ALIMENTAIRE / FRAIS/FROMAGE
    448,  # ALIMENTAIRE / FRAIS / POISSONNERIE
]
